### ISSUE TITLE
Run CsvJoinWithEsExample example error,  maybe antlr4 jar is Incompatible

### ISSUE THREAD

**Issue by louis83** [Qihoo360/Quicksql#18] opened 2019-01-18 02:37 UTC
the error message is：
ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.5.3ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:84)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseTableIdentifier(ParseDriver.scala:49)
	at org.apache.spark.sql.Dataset.createTempViewCommand(Dataset.scala:3142)
	at org.apache.spark.sql.Dataset.createOrReplaceTempView(Dataset.scala:3097)
	at Requirement35141.execute(Requirement35141.java:75)
	at com.qihoo.qsql.exec.result.JobPipelineResult.run(JobPipelineResult.java:39)
	at com.qihoo.qsql.CsvJoinWithEsExample.main(CsvJoinWithEsExample.java:23)
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:153)
	at org.apache.spark.sql.catalyst.parser.SqlBaseLexer.<clinit>(SqlBaseLexer.java:1175)
	... 8 more
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	... 10 more

**Comment by Functor10** [comment] 2019-01-18 03:48
Hi, this error maybe caused by a conflict between qsql and spark, you can try to set `spark.driver.userClassPathFirst=true` in **qsql-runner.properties**, this configuration item is closed by default.

**Comment by zihengCat** [comment] 2019-01-21 01:31
Same problem, and set `spark.driver.userClassPathFirst=true` in **conf/qsql-runner.properties** does not work. @Functor10 
![screenshot from 2019-01-21 09-28-34](https://user-images.githubusercontent.com/19472493/51448111-2d436180-1d5f-11e9-871c-72281578add1.png)

**Comment by lianneli** [comment] 2019-01-21 14:34
This Exception happens when compiling with Spark2.3+ but running with Spark2.2-.
Spark2.3 dependes on antlr4-runtime-4.7.jar, which conflicts with antlr4-runtime-4.5.3.jar that Spark2.2 needs. We will solve this issue in the new PR.

**Closed as completed** 2019-01-29 06:22 UTC
Labels: good first issue
